title: "Configure ApplicationPool for Pydio in Windows2012 & IIS8 [Update Pydio 6]" 
language: en
category: Security
tags:
  application pool
  iis8
  iis_iusrs
  process worker
  virtual directory
  windows 2012
  windows server
  windows server 2012