title: "Configuring public link on Pydio 6"
language: en
category: 
  System
  Miscellaneous
tags: 
  apache
  htaccess
  iis
  nginx
  public folder
  public share link
  rewrite
  rewritemodule
  share link
  webconfig